### ISSUE TITLE
NanoPB and Contiki

### ISSUE THREAD

**Issue by arurke** [feshie/contiki#29]
Hi, more a question than an issue:

I have been looking into more efficient ways of sending data from my Contiki nodes, and protocol buffers has been at the top of my list. I then stumbled upon your usage of protocol buffers and NanoPB in Contiki. Can I just ask what are your experiences using this? Any thoughts or evaluations you did regarding CPU, RAM or ROM would be especially interesting. Or maybe you have any newfound opinions on serialization mechanisms?

Regards,
Andreas U.
www.netwurke.com

**Comment by kmartinez** [comment]
yes we have deployed a test system with protocol buffers as the main format for data and configuration - it saves a lot of bandwidth, flash space etc. We did not notice CPU load even on a zolertia Z1 (msp430) and the library fitted OK.. but I am sure we ended up making a few modifications somewhere. You can check our code for the feshie nodes...

**Comment by arthurfabre** [comment]
Hi Andreas,

As far I know we used vanilla (ie no modifications) nanoPB.
The RAM usage is negligible compared to the buffers needed to encode / decode / send the data, I'm not sure on the ROM usage however (but as Kirk mentions, we had no issue getting Contiki+nanopb on the msp430).
I think we were all very happy with protocol buffers overall.

**Comment by arurke** [comment]
Thanks for the feedback! From the repo it seems you are using vanilla since nanoPB is a submodule and the commit is on the master branch. I will definitely check it out.

**Comment by arurke** [comment]
Hi, a few more before I start implementing:

1. How do you decode the messages server-side? I can't find any specific information on the nanoPBs interoperability with other implementations, but I assume I would need to run nanoPB on the server as well?

2. Did you ever evaluate MessagePack? It seems simpler (no need to create templates), and is tailored for JSON which is what we want at the server-side. Drawback though, seems that there are no "tiny" implementations.

Regards,
Andreas

**Comment by arthurfabre** [comment]
Hi Andreas,

1. nanopb implements the protocol buffer specification, you can therefore decode messages using any protocol buffer library. We have a [separate repo](https://github.com/feshie/protocol-buffers) that contains our message definitions, and generates:
   * A library for C using nanopb. We use this on the nodes.
   * Libraries for Java and Python using the google implementation (protoc). We use both to decode messages from the nodes, and haven't had any issues.

2. I'm not familiar with MessagePack, but one of the reasons for using protocol buffers was small messages sizes, and a small implementation that works on our nodes. (I believe we initially used plain JSON before).

**Comment by arurke** [comment]
Thanks again, and of course when I think about no.1 it is obvious. It also seems protobuf is an easy pick, at least when aiming for dev. speed.
